name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make gradlew executable
        run: cd .. && cd android && chmod +x ./gradlew
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: cd .. && cd android && ./gradlew build
