  
name: ci
on: [pull_request]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

  # build-ios:
  #   needs: install-and-test
  #   runs-on: [self-hosted, macos]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Install POD dependencies
  #       run: cd ios && pod install

  #     - name: Build app
  #       run: |
  #         xcodebuild -workspace cepapp.xcworkspace -scheme cepapp archive -archivePath cepapp.xcarchive -allowProvisioningUpdates
  #         xcodebuild -exportArchive -archivePath ./cepapp.xcarchive -exportPath . -exportOptionsPlist cepapp/Info.plist
  #         mv cepapp.ipa ../cepapp.ipa
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: cepapp.ipa
  #         path: ios/build/
